### ISSUE TITLE
Copy & Paste Object on designer

### ISSUE THREAD

**Issue by bdbais** [dbeck121/ConVista-CPI-Helper-Chrome-Extension#3]
Hi could you add Copy/Cut/Paste/Undo on your plugin so we can use them on designer?
On Trace(message content) tab you add beautify function, could you add xpath evaluate and create map with alla fields 1-1 or xpath copy from curson position (like in notepad++)?

**Comment by dbeck121** [comment]
Hi,
thank you for your suggestions. 

- I think copy/cut/paste/undo is not possible because the API from the CPI does not provide anything for this. I would love that feature but I do not think it is possible. The chrome extension also has no access to the javascript from sap to make such operations.
- what do you mean with a map of all fields?
- I will think about the XPath feature. What do you want to evaluate with XPath. Isn't it more a general new feature instead a feature of the beautifier/trace tab?

Unfortunately I have only limited time. The plug-in is open source, so you are welcome to send pull requests yourself ;-)

**Comment by dbeck121** [comment]
no answer. closed

**Comment by bdbais** [comment]
I will check source code and add some other feature

**Comment by bdbais** [comment]
Other feature: Automatic save as version activate.

**Comment by dbeck121** [comment]
The problem is, that you do not have access to the sites javascript. So unfortunately we are very limited. But if you have a good idea and provide me a pull request, I will include your code :-)
